env:
  APP_ENV: development
  LOG_LEVEL: debug

ingress:
  enabled: true
  host: dev.react.local

replicaCount: 1

image:
  tag: dev
  pullPolicy: Never

service:
  type: NodePort
  nodePort: 30007

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

